mounting_params:
  left:
    base_x: 0
    base_y: -0.3
    base_z: 1.0
    base_R: 0.0
    base_P: 1.57
    base_Y: 0
  right:
    base_x: 0.0 
    base_y: 0.3
    base_z: 1.0
    base_R: 0.0 
    base_P: 1.57
    base_Y: 0
  single:
    base_x: 0.0 
    base_y: 0.0
    base_z: 1.0
    base_R: 0.0 
    base_P: 1.57
    base_Y: 0
  

table_params:
    base_x: 0.0
    base_y: 1.0
    base_z: 0.0
    base_R: 0.0
    base_P: 0.0
    base_Y: 0.0

initial_joint_angles:
    left: [0, -3.0, 1.75, -1.9, -1.5, 0]
    right: [0, -3.0, 1.75, -1.9, -1.5, 0]